name: "Aether Vault"
description: "Sovereane secret management and security policy enforcement for Aether Office ecosystem"
author: "Sky Genesis Enterprise"
branding:
  icon: "shield"
  color: "purple"

inputs:
  vault-url:
    description: "Aether Vault server URL"
    required: true
  auth-method:
    description: "Authentication method (github-oidc)"
    required: true
    default: "github-oidc"
  role:
    description: "Vault role for authentication"
    required: false
  policy-mode:
    description: "Policy enforcement mode (enforce|audit)"
    required: false
    default: "enforce"
  audience:
    description: "OIDC audience for token exchange"
    required: false
    default: "aether-vault"
  allow-token-output:
    description: "Allow vault token in outputs (security-sensitive)"
    required: false
    default: "false"

outputs:
  status:
    description: "Policy check status (success|violation)"
  report-id:
    description: "Audit report ID for correlation"
  vault-token:
    description: "Vault token (if allowed by policy)"

runs:
  using: "composite"
  steps:
    - name: Execute Aether Vault Action
      uses: ./package/action
      with:
        vault-url: ${{ inputs.vault-url }}
        auth-method: ${{ inputs.auth-method }}
        role: ${{ inputs.role }}
        policy-mode: ${{ inputs.policy-mode }}
        audience: ${{ inputs.audience }}
        allow-token-output: ${{ inputs.allow-token-output }}
