name: "Aether Vault Action"
description: "Authenticate with Aether Vault and perform security policy checks"
author: "Sky Genesis Enterprise"

inputs:
  vault-url:
    description: "Aether Vault server URL"
    required: true
  auth-method:
    description: "Authentication method (github-oidc)"
    required: true
    default: "github-oidc"
  role:
    description: "Vault role for authentication"
    required: false
  policy-mode:
    description: "Policy enforcement mode (enforce|audit)"
    required: false
    default: "enforce"
  audience:
    description: "OIDC audience for token exchange"
    required: false
    default: "aether-vault"
  allow-token-output:
    description: "Allow vault token in outputs (security-sensitive)"
    required: false
    default: "false"

outputs:
  status:
    description: "Policy check status (success|violation)"
  report-id:
    description: "Audit report ID for correlation"
  vault-token:
    description: "Vault token (if allowed by policy)"

runs:
  using: "composite"
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.5"

    - name: Execute Aether Vault binary
      shell: bash
      env:
        VAULT_URL: ${{ inputs.vault-url }}
        AUTH_METHOD: ${{ inputs.auth-method }}
        ROLE: ${{ inputs.role }}
        POLICY_MODE: ${{ inputs.policy-mode }}
        AUDIENCE: ${{ inputs.audience }}
        ALLOW_TOKEN_OUTPUT: ${{ inputs.allow-token-output }}
      run: |
        # Determine platform and architecture
        PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        # Map architecture names
        case $ARCH in
          x86_64) ARCH="amd64" ;;
          aarch64|arm64) ARCH="arm64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        BINARY_NAME="aether-vault-${PLATFORM}-${ARCH}"
        BINARY_PATH="${{ github.action_path }}/bin/${BINARY_NAME}"

        if [ ! -f "$BINARY_PATH" ]; then
          echo "❌ Binary not found: $BINARY_PATH"
          echo "Available binaries:"
          ls -la "${{ github.action_path }}/bin/" || echo "No bin directory found"
          exit 1
        fi

        echo "🚀 Executing Aether Vault Action"
        echo "Binary: $BINARY_PATH"
        echo "Platform: $PLATFORM"
        echo "Architecture: $ARCH"

        chmod +x "$BINARY_PATH"
        exec "$BINARY_PATH"
